name: fantastic_assistant
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.3
  get_it: ^7.6.4
  injectable: ^2.3.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  cloud_firestore: ^4.9.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.1

flutter:
  uses-material-design: true
  assets:
  - .env
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
