name: fantastic_assistant
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.3
  get_it: ^7.6.4
  injectable: ^2.3.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  cloud_firestore: ^4.15.9
  equatable: ^2.0.5
  image_picker: ^1.0.4
  firebase_storage: ^11.2.8
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.2.0
  device_info_plus: ^9.1.0
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.2
  build_runner: ^2.4.6
  injectable_generator: ^2.5.1
  auto_route_generator: ^7.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb-Light.ttf
          weight: 100
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
