Map<String, String> dndHints = {
  "attributes":
      "Each of a creature’s abilities has a score, a number that defines the magnitude of that ability. An ability score is not just a measure of innate capabilities, but also encompasses a creature’s training and competence in activities related to that ability.\nA score of 10 or 11 is the normal human average, but adventurers and many monsters are a cut above average in most abilities. A score of 18 is the highest that a person usually reaches. Adventurers can have scores as high as 20, and monsters and divine beings can have scores as high as 30.\nEach ability also has a modifier, derived from the score and ranging from −5 (for an ability score of 1) to +10 (for a score of 30). The Ability Scores and Modifiers table notes the ability modifiers for the range of possible ability scores, from 1 to 30.",
  "proficiency":
      "Unique to 5th edition, instead of putting points into individual skills you have a general purpose \"proficiency bonus\" that's based on your level and is applied to attack rolls, saving throws, and skill checks if you're proficient in that task. Under You will find list of how many proficiency points on each level:\nLevel 1 - 2\nLevel 2 - 2\nLevel 3 - 2\nLevel 4 - 2\nLevel 5 - 3\nLevel 6 - 3\nLevel 7 - 3\nLevel 8 - 3\nLevel 9 - 4\nLevel 10 - 4\nLevel 11 - 4\nLevel 12 - 4\nLevel 13 - 5\nLevel 14 - 5\nLevel 15 - 5\nLevel 16 - 5\nLevel 17 - 6\nLevel 18 - 6\nLevel 19 - 6\nLevel 20 - 6\n",
  "armorClass":
      "When unarmored, your base Armor Class is 10 + Dexterity modifier. If you have a spell, item, feat, or racial trait that affects your Armor Class then the calculation will change. The two most common ways to increase AC are to pump your Dexterity modifier (if you’re not wearing heavy armor) or to equip better armor.",
  "initiative":
      "Initiative is a crucial aspect of combat in Dungeons & Dragons as it determines the order in which each creature takes their turn. When calculating initiative, there are a few things to note. Each creature has an Initiative Bonus, which is equal to their Dexterity Modifier, plus any bonuses they have from feats, classes, and such, which will state the bonuses they grant. When initiative is called, each creature acts from highest initiative to lowest.",
  "speed":
      "Every character and monster has a speed, which is the distance in feet that the character or monster can walk in 1 round. This number assumes short bursts of energetic movement in the midst of a life- threatening situation.",
  "hp":
      "Your character’s hit points define how tough your character is in combat and other dangerous situations. Your hit points are determined by your Hit Dice (short for Hit Point Dice).\nAt 1st level, your character has 1 Hit Die, and the die type is determined by your class. You start with hit points equal to the highest roll of that die, as indicated in your class description. (You also add your Constitution modifier, which you’ll determine in step 3.) This is also your hit point maximum",
};
