List<String> listOfSkills = [
  'Athletics',
  'Acrobatics',
  'Sleight of Hand',
  'Stealth',
  'Arcana',
  'History',
  'Investigation',
  'Nature',
  'Religion',
  'Animal Handling',
  'Insight',
  'Medicine',
  'Perception',
  'Survival',
  'Deception',
  'Intimidation',
  'Performance',
  'Persuasion',
];

// Map<String, String> mapSkillsAndTheirAttribute = {
//   'Athletics': 'strength',
//   'Acrobatics': 'dexterity',
//   'Sleight of Hand': 'dexterity',
//   'Stealth': 'dexterity',
//   'Arcana': 'intelligence',
//   'History': 'intelligence',
//   'Investigation': 'intelligence',
//   'Nature': 'intelligence',
//   'Religion': 'intelligence',
//   'Animal Handling': 'wisdom',
//   'Insight': 'wisdom',
//   'Medicine': 'wisdom',
//   'Perception': 'wisdom',
//   'Survival': 'wisdom',
//   'Deception': 'charisma',
//   'Intimidation': 'charisma',
//   'Performance': 'charisma',
//   'Persuasion': 'charisma',
// };
